#!/bin/sh

#This function verify is the package name is correct
# No spaces and other requirements
fn_verifyPackage() {
    pkgName="$@"
    goldsteinExtension="gds"

    #Checking for file extension
    if ! echo "$pkgName" | grep "\b${goldsteinExtension}\b"; then
        printf '%s\n' "The file extension should be ${goldsteinExtension}"
        exit 1
    fi

    #Checking for spaces in package name
    if echo $pkgName | grep -qE "[[:space:]]+"; then
        printf "Don't use spaces on your package name\n"
        exit 1
    fi

    #Checking hyphen count
    hyphenCount=$(echo "${pkgName}" | grep -qo "-" | wc -l)
    if [ "$hyphenCount" -lt '2' ] || [ "$hyphenCount" -gt '2' ]; then
        printf '%s\n' "Too much hyphens! follow the pattern"
        printf '%s\n' "packagename-version-build"
        exit 1
    fi

}

# This function creates .gds packages
fn_createPkg() {
    pkgName="$1"

    if tar -cvf ../${pkgName} .; then
        printf '%s\n' "Package createad ../${pkgWithGoldsteinExtension}"
        return 0
    else
        printf '%s\n' "Couldn't crete ${pkgWithGoldsteinExtension}"
        exit 1
    fi
}

case "$1" in
create | -c)
    shift                # Taking package name
    if [ -z "$1" ]; then #If $1 is null
        printf '%s\n' "Package name is null"
        exit 1
    fi
    fn_verifyPackage "$@" #Veryfing prerequisites
    fn_createPkg "$@"
    ;;
esac
